### ISSUE TITLE
The Weather Channel app shows blank space, no card when ProSwitcher invoked

### ISSUE THREAD

**Issue by Bripab007** [rpetrich/ProSwitcher#107]
When running the Weather Channel app, if you invoke ProSwitcher, there is no screenshot or card created for the app. Instead, simply a blank space exists, with no title and is not selectable. When this happens, other functionality seems to be unaffected, allowing you to continue using the phone as normal. Also, manually launching the Weather Channel app again from the springboard shows it is still running, and normal operation continues.

**Comment by Bripab007** [comment]
This appears to have been fixed in the latest update.

**Comment by grp** [comment]
Awesome, not sure what fixed htis.

**Comment by rpetrich** [comment]
Magic fix! :P

**Comment by sysrage** [comment]
Other apps where I saw the same behavior are also fixed. Hopefully it's not fixed by the screwy new app launch animation and will break again when you fix that. ;)
